### PR TITLE
Update Signature API version.

### PR DESCRIPTION
**Pull request by kegor**
Replicated changes from https://github.com/groupdocs-signature/GroupDocs.Signature-for-.NET-MVC/pull/32.

### CODE REVIEW

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Complexity increasing per file
==============================
- src/AppDomainGenerator/DomainGenerator.cs  2
         

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Signature-for-.NET-WebForms/pullRequest?prid=5327692&bid=17437720)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 16
           

Complexity increasing per file
==============================
- src/AppDomainGenerator/DomainGenerator.cs  2
         

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-signature/GroupDocs.Signature-for-.NET-WebForms/pullRequest?prid=5327693&bid=17437721)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 16
           

Complexity increasing per file
==============================
- src/AppDomainGenerator/DomainGenerator.cs  2
         

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-signature/GroupDocs.Signature-for-.NET-WebForms/pullRequest?prid=5327693&bid=17437721)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Complexity increasing per file
==============================
- src/AppDomainGenerator/DomainGenerator.cs  2
         

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Signature-for-.NET-WebForms/pullRequest?prid=5327692&bid=17437720)

**Review by Pavel-Teplitsky — APPROVED** [review]

**Pull request merged**
